services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      GOSEARCH_BACKEND_PORT: "8080"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
